### ISSUE TITLE
on-chain-indicators.parquet File missing

### ISSUE THREAD

**Issue by carlosmassa** [evandroagnes/cryptocurrencies-trading#22]
Hi!

I'm trying to run your notebook below, but the file "filename = 'data/on-chain-indicators.parquet'" is missing, so I am getting an error.

 [cryptocurrencies-trading](https://github.com/evandroagnes/cryptocurrencies-trading)/cryptocurrencies_price_prediction.ipynb

Would you mind uploading that file to the repo or advising what should be in that file?

Thanks!

**Comment by evandroagnes** [comment]
Hi Carlos! Sure, I forgot to deal with the notebook first run. I committed the fix for this bug right now. Could you test again?

Remember to create an api-key from glassnode before. The Standard free plan is sufficient. Thanks!

**Comment by carlosmassa** [comment]
Hi Evandro,

Thanks for the prompt reply. I do have the free plan api-key from glassnode already. however, the notebook is not working yet.

Sorry, the notebook I was trying to run is the one below:

https://github.com/evandroagnes/cryptocurrencies-trading/blob/master/cryptocurrencies_on-chain_analysis.ipynb

And the issue I'm facing is with the piece of code below:


#https://coinmetrics.io/introducing-the-revamped-coin-metrics-python-api-client/
from coinmetrics.api_client import CoinMetricsClient

gather_new_data = False
filename = 'data/on-chain-indicators.parquet'

try:
    table = pq.read_table(filename)
    metrics = table.to_pandas()
    last_date = metrics.index[-1].date()
    gather_new_data = last_date < date.today() - relativedelta(days = 1)
except FileNotFoundError:
    gather_new_data = True

I am missing the file "data/on-chain-indicators.parquet". I can't find it in your repo, so when running it:

FileNotFoundError: data/on-chain-indicators.parquet

Can you share the content of this file?
